// 解析小组件参数（支持中文名、纯ID、或 JSON {"id":"xxxxx"}） function resolveCityId(input) { const raw = String(input || "").trim(); if (!raw) return CITY_NAME_TO_ID["南京"] || "101190101"; if (raw.startsWith("{")) { try { const obj = JSON.parse(raw); if (obj && typeof obj.id === "string" && obj.id.trim()) return obj.id.trim(); } catch {} } if (/^\d{6,}$/.test(raw)) return raw; const name = raw.replace(/市$/, ""); return CITY_NAME_TO_ID[name] || CITY_NAME_TO_ID["南京"] || "101190101"; }

function aqiColor(quality, aqi) { const q = String(quality || ""); const n = Number(aqi || NaN); if (q.includes("优") || (!isNaN(n) && n <= 50)) return $color("#16a34a");   // 绿 if (q.includes("良") || (!isNaN(n) && n <= 100)) return $color("#f59e0b"); // 橙 return $color("#ef4444"); // 红 }

function weatherEmoji(text) { const t = String(text || ""); if (t.includes("雷")) return "⛈️"; if (t.includes("雨")) return "🌧️"; if (t.includes("雪")) return "❄️"; if (t.includes("雾") || t.includes("霾") || t.includes("沙")) return "🌫️"; if (t.includes("阴")) return "☁️"; if (t.includes("云")) return "⛅️"; if (t.includes("晴")) return "☀️"; return "🌡️"; }

async function fetchMeizu(cityId) { const base = "http://aider.meizu.com/app/weather/listWeather?cityIds="; const url = CONFIG.useProxy ? (CONFIG.proxyBase + encodeURIComponent(cityId)) : (base + encodeURIComponent(cityId)); const resp = await $http.get({ url, header: { "Accept": "application/json" } }); if (!resp || !resp.data) throw new Error("网络无响应"); const j = resp.data; if (j.code !== 200 && j.code !== "200") { throw new Error(j.message || 接口返回码：${j.code}); } const arr = j.value || []; if (!arr.length) throw new Error("未找到该城市天气"); const d = arr[0]; const rt = d.realtime || {}; const air = d.pm25 || {}; return { city: d.city, temp: rt.temp || "--", weather: rt.weather || "—", humidity: rt.sD ? (rt.sD + "%") : "—", wind: [rt.wD, rt.wS].filter(Boolean).join(" ") || "—", aqi: air.aqi || "", quality: air.quality || "—", updateTime: rt.time || air.upDateTime || "—", emoji: weatherEmoji(rt.weather) }; }

function smallView(info) { return { type: "vstack", props: { alignment: "leading", spacing: 6 }, views: [ { type: "text", props: { text: info.city, color: $color("secondary"), font: $font(12) } }, { type: "hstack", props: { alignment: "center", spacing: 8 }, views: [ { type: "text", props: { text: info.emoji, font: $font(24) } }, { type: "text", props: { text: ${info.temp}°C, font: $font("bold", 24) } } ] }, { type: "text", props: { text: info.weather, color: $color("secondary"), font: $font(12) } } ] }; }

function mediumView(info) { return { type: "vstack", props: { alignment: "leading", spacing: 6 }, views: [ { type: "text", props: { text: ${info.city} · ${info.weather}, font: $font("bold", 14) } }, { type: "hstack", props: { spacing: 10 }, views: [ { type: "text", props: { text: info.emoji, font: $font(22) } }, { type: "text", props: { text: 气温 ${info.temp}°C, font: $font(14) } }, { type: "text", props: { text: 湿度 ${info.humidity}, font: $font(14) } }, { type: "text", props: { text: 风 ${info.wind}, font: $font(14) } } ] }, { type: "hstack", props: { spacing: 8 }, views: [ { type: "text", props: { text: "空气 ", font: $font(12), color: $color("secondary") } }, { type: "text", props: { text: ${info.quality}${info.aqi ? " · AQI " + info.aqi : ""}, font: $font(12), color: aqiColor(info.quality, info.aqi) } }, { type: "text", props: { text: 更新时间 ${info.updateTime}, font: $font(11), color: $color("secondary") } } ] } ] }; }

function largeView(info) { // 简化版：与中号一致，可按需加未来3小时预报 return { type: "vstack", props: { alignment: "leading", spacing: 8 }, views: [ { type: "text", props: { text: ${info.city} · ${info.weather}, font: $font("bold", 16) } }, { type: "hstack", props: { spacing: 12 }, views: [ { type: "text", props: { text: info.emoji, font: $font(26) } }, { type: "text", props: { text: 气温 ${info.temp}°C, font: $font(16) } }, { type: "text", props: { text: 湿度 ${info.humidity}, font: $font(16) } }, { type: "text", props: { text: 风 ${info.wind}, font: $font(16) } } ] }, { type: "hstack", props: { spacing: 8 }, views: [ { type: "text", props: { text: "空气 ", font: $font(14), color: $color("secondary") } }, { type: "text", props: { text: ${info.quality}${info.aqi ? " · AQI " + info.aqi : ""}, font: $font(14), color: aqiColor(info.quality, info.aqi) } } ] }, { type: "text", props: { text: 更新时间 ${info.updateTime}, font: $font(12), color: $color("secondary") } } ] }; }

function errorView(msg) { return { type: "vstack", props: { alignment: "leading", spacing: 6 }, views: [ { type: "text", props: { text: "魅族天气", font: $font("bold", 14) } }, { type: "text", props: { text: msg, color: $color("#ef4444"), font: $font(12) } }, { type: "text", props: { text: "如 http 被拦截，请开启代理。", color: $color("secondary"), font: $font(11) } } ] }; }

// 渲染与时间线 $widget.setTimeline({ render: async (ctx) => { try { // 优先使用小组件参数（Egern 通常是 $widget.inputValue），否则用默认值 const param = (typeof $widget.inputValue === "string" ? $widget.inputValue : "") || CONFIG.defaultCityOrId; const cityId = resolveCityId(param); const info = await fetchMeizu(cityId); if (ctx.family === "small") return smallView(info); if (ctx.family === "large") return largeView(info); return mediumView(info); } catch (e) { const msg = (e && e.message) ? e.message : String(e); return errorView(msg); } }, policy: { after: new Date(Date.now() + Math.max(3, CONFIG.refreshMinutes) * 60 * 1000) } });